name: 04-using-actions.yaml

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: printing folders
        run: ls -ltrh

