name: 13 - using caching

on:
  workflow_dispatch: 
    inputs:
      use-cache:
        description: whether to execute cache step
        type: boolean
        default: true
      node-version:
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUTS"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
          
  linting:
    runs-on: ubuntu-latest
    needs: 
      - install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with: 
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key}} 
      - name: Testing
        run: npm run test
      - name: Linting
        run: echo "Linting..."   

  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: 13-caching/react-app
    needs:
      - install-deps
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
      - name: Building
        run: npm run build
      - name: Deploying 
        run: echo "Deploy code to nonprod"

  
# 1. checkout the code.
# 2. Install dependencies
# 3. linting, formating, unit testing, building
# 4. deploy code to nonprod environment
